### ISSUE TITLE
Crash on Missing File

### ISSUE THREAD

**Issue by xavierholt** [UCSB-CS56-Projects/cs56-games-fish-animation#72]
Got this just after entering my name at the end of a game.

100 XP

```
[17:33:34 holt@Minerva fish]$ ant run
Buildfile: /Users/holt/Code/cs56/fish/build.xml

compile:

run:
     [java] java.io.FileNotFoundException: saved.ser (No such file or directory)
     [java] 	at java.base/java.io.FileInputStream.open0(Native Method)
     [java] 	at java.base/java.io.FileInputStream.open(FileInputStream.java:196)
     [java] 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:139)
     [java] 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:94)
     [java] 	at edu.ucsb.cs56.projects.games.fish_animation.FishAnimationEnvironment.<init>(FishAnimationEnvironment.java:200)
     [java] 	at edu.ucsb.cs56.projects.games.fish_animation.Menu.actionPerformed(Menu.java:626)
     [java] 	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
     [java] 	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
     [java] 	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
     [java] 	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
     [java] 	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:269)
     [java] 	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
     [java] 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6578)
     [java] 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3343)
     [java] 	at java.desktop/java.awt.Component.processEvent(Component.java:6343)
     [java] 	at java.desktop/java.awt.Container.processEvent(Container.java:2259)
     [java] 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4961)
     [java] 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2317)
     [java] 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4793)
     [java] 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
     [java] 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4539)
     [java] 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4480)
     [java] 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2303)
     [java] 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2758)
     [java] 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4793)
     [java] 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
     [java] 	at java.desktop/java.awt.EventQueue.access$500(EventQueue.java:97)
     [java] 	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:717)
     [java] 	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:711)
     [java] 	at java.base/java.security.AccessController.doPrivileged(Native Method)
     [java] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)
     [java] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:99)
     [java] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:739)
     [java] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:737)
     [java] 	at java.base/java.security.AccessController.doPrivileged(Native Method)
     [java] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)
     [java] 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
     [java] 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199)
     [java] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
     [java] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
     [java] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
     [java] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
     [java] 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
     [java] java.lang.NullPointerException
     [java] Java Result: 1

BUILD SUCCESSFUL
Total time: 47 seconds
```

**Comment by xavierholt** [comment]
Looked into this a bit more.  All is not as it seems...

200 XP

**Comment by aryamandas** [comment]
W18 OK (200 points)
